version: '3.1'
services:
        database-service:
                build: ./database
                ports:
                        - 3306:3306
        webapp-service:
                build: ./webapp
                ports:
                        - 80:80
                depends-on:
                        - database-service
